backend:
  name: github
  repo: Shogun181/ngin3
  branch: main
  auth_type: implicit

local_backend: true # Allows local editing when using live server
public_folder: "/assets/images"

collections:
  - name: "settings"
    label: "Wedding Details"
    files:
      - file: "data/wedding.json"
        label: "Configuration"
        name: "wedding_config"
        fields:
          - { label: "Bride Name", name: "brideName", widget: "string" }
          - { label: "Groom Name", name: "groomName", widget: "string" }
          - { label: "Wedding Date", name: "date", widget: "string" }
          - { label: "Venue", name: "venue", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Cover Photo", name: "heroImage", widget: "image" }
